spring.application.name=equis



spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/equis}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.user.name=user

spring.mustache.suffix=.html
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG


spring.mustache.cache=false
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=redsocialequis@gmail.com
spring.mail.password=gjua pjfy rvnb jvju
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat